import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('window');
import COLORS from '../../constants/colors';

const SignUpStyles = StyleSheet.create({
  parentView: {height: '100%', width: '100%', marginTop: 24},
  scrollViewContainer: {
    height: '100%',
    width: '100%',
    marginBottom: 60,
  },
  authorImage: {width: 24, height: 24},
  authorView: {flexDirection: 'row', marginTop: 10, alignItems: 'center'},
  contextBackground: {
    width: '100%',
    height: 410,
  },
  gradientText: {fontWeight: '600', fontSize: 20},
  separator: {
    height: 1,
    width: 70,
    backgroundColor: 'blue',
    marginTop: 10,
  },
  starterParent: {
    alignItems: 'center',
    marginTop: '6%',
    backgroundColor: '#FFFBF1',
    paddingBottom: '10%',
  },
  starterListDesc: {marginTop: 10, width: '80%'},
  starterlistHeading: {marginTop: 10, width: '80%'},
  starterListImage: {width: 300, height: 100},
  starterItem: {marginTop: 20, marginStart: 10, width: 350, paddingBottom: 20},
  signupNow: {fontSize: 24, marginTop: 20, marginHorizontal: '14%'},
  missionContainer: {alignItems: 'center', marginTop: '4%'},
  missionText1: {marginTop: '3%', fontWeight: '600', fontSize: 20},
  contextHeading: {position: 'absolute', top: '30%', start: '10%'},
  margin10: {marginTop: 10},
  tickIcon: {width: 24, height: 20},
  StarterCardContainer: {
    width: '90%',
    backgroundColor: '#F3F5FF',
    paddingTop: 20,
    paddingHorizontal: 10,
    paddingBottom: 20,
    margin: 10,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'blue',
  },
  StarterCredits: {
    fontSize: 18,
    fontWeight: '500',
    marginStart: 10,
    marginTop: -5,
    width: '90%',
    marginBottom: 20,
  },
  starterText: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
  },
  signUpFree: {
    width: '90%',
    height: 36,
    marginStart: 12,
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  getStartedButton: {
    width: '84%',
    height: 36,
    marginStart: 12,
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  startReadingText: {marginTop: '24%'},
  getStartedContainer: {marginTop: '8%'},
  headerContainer: {
    backgroundColor: COLORS.WHITE,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
  },
  menuIcon: {width: 20, height: 20, marginStart: 20},
  ellipseIcon: {width: 120, height: 40, marginStart: 20},
  searchIcon: {width: 24, height: 24, marginStart: 60},
  signUpButton: {
    width: 100,
    height: 36,
    marginStart: 6,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginEnd: 10,
  },
  descriptionContainer: {alignItems: 'center', marginTop: '8%'},
  descriptionItem: {
    width: '90%',
    backgroundColor: '#F3F5FF',
    paddingTop: 20,
    paddingHorizontal: 10,
    paddingBottom: 10,
    margin: 10,
    borderRadius: 6,
  },
  descriptionIcon: {height: 24, width: 24},
  descriptionHeading: {
    fontSize: 18,
    fontWeight: '500',
    marginStart: 10,
    marginTop: -5,
    width: '90%',
  },
});
export default SignUpStyles;
